let citiesArray = [
  {name: "ACT", timezones: "Australia/ACT" },
  {name: "Abidjan", timezones: "Africa/Abidjan" },
  {name: "Accra", timezones: "Africa/Accra" },
  {name: "Acre", timezones: "Brazil/Acre" },
  {name: "Adak", timezones: "America/Adak" },
  {name: "Addis Ababa", timezones: "Africa/Addis_Ababa" },
  {name: "Adelaide", timezones: "Australia/Adelaide" },
  {name: "Aden", timezones: "Asia/Aden" },
  {name: "Alaska", timezones: "US/Alaska" },
  {name: "Aleutian", timezones: "US/Aleutian" },
  {name: "Algiers", timezones: "Africa/Algiers" },
  {name: "Almaty", timezones: "Asia/Almaty" },
  {name: "Amman", timezones: "Asia/Amman" },
  {name: "Amsterdam", timezones: "Europe/Amsterdam" },
  {name: "Anadyr", timezones: "Asia/Anadyr" },
  {name: "Anchorage", timezones: "America/Anchorage" },
  {name: "Andorra", timezones: "Europe/Andorra" },
  {name: "Anguilla", timezones: "America/Anguilla" },
  {name: "Antananarivo", timezones: "Indian/Antananarivo" },
  {name: "Antigua", timezones: "America/Antigua" },
  {name: "Apia", timezones: "Pacific/Apia" },
  {name: "Aqtau", timezones: "Asia/Aqtau" },
  {name: "Aqtobe", timezones: "Asia/Aqtobe" },
  {name: "Araguaina", timezones: "America/Araguaina" },
  {name: "Arctic", timezones: "Arctic/Longyearbyen" },
  {name: "Arizona", timezones: "US/Arizona" },
  {name: "Arkhangelsk", timezones: "Europe/Arkhangelsk" },
  {name: "Ashgabat", timezones: "Asia/Ashgabat" },
  {name: "Ashkhabad", timezones: "Asia/Ashkhabad" },
  {name: "Asmara", timezones: "Africa/Asmara" },
  {name: "Asmera", timezones: "Africa/Asmera" },
  {name: "Astana", timezones: "Asia/Oral" },
  {name: "Asuncion", timezones: "America/Asuncion" },
  {name: "Athens", timezones: "Europe/Athens" },
  {name: "Atikokan", timezones: "America/Atikokan" },
  {name: "Auckland", timezones: "Pacific/Auckland" },
  {name: "Azores", timezones: "Atlantic/Azores" },
  {name: "Baghdad", timezones: "Asia/Baghdad" },
  {name: "Bahia", timezones: "America/Bahia" },
  {name: "Bahia Banderas", timezones: "America/Bahia_Banderas" },
  {name: "Bahrain", timezones: "Asia/Bahrain" },
  {name: "Baku", timezones: "Asia/Baku" },
  {name: "Bamako", timezones: "Africa/Bamako" },
  {name: "Bangkok", timezones: "Asia/Bangkok" },
  {name: "Bangui", timezones: "Africa/Bangui" },
  {name: "Banjul", timezones: "Africa/Banjul" },
  {name: "Barbados", timezones: "America/Barbados" },
  {name: "Barnaul", timezones: "Asia/Barnaul" },
  {name: "Beirut", timezones: "Asia/Beirut" },
  {name: "Belem", timezones: "America/Belem" },
  {name: "Belfast", timezones: "Europe/Belfast" },
  {name: "Belgrade", timezones: "Europe/Belgrade" },
  {name: "Belize", timezones: "America/Belize" },
  {name: "Berlin", timezones: "Europe/Berlin" },
  {name: "Bermuda", timezones: "Atlantic/Bermuda" },
  {name: "Beulah", timezones: "America/North_Dakota/Beulah" },
  {name: "Bishkek", timezones: "Asia/Bishkek" },
  {name: "Bissau", timezones: "Africa/Bissau" },
  {name: "Blanc Sablon", timezones: "America/Blanc-Sablon" },
  {name: "Blantyre", timezones: "Africa/Blantyre" },
  {name: "Boa Vista", timezones: "America/Boa_Vista" },
  {name: "Bogota", timezones: "America/Bogota" },
  {name: "Boise", timezones: "America/Boise" },
  {name: "Bougainville", timezones: "Pacific/Bougainville" },
  {name: "Bratislava", timezones: "Europe/Bratislava" },
  {name: "Brazil", timezones: "Brazil/East" },
  {name: "Brazzaville", timezones: "Africa/Brazzaville" },
  {name: "Brisbane", timezones: "Australia/Brisbane" },
  {name: "Broken Hill", timezones: "Australia/Broken_Hill" },
  {name: "Brunei", timezones: "Asia/Brunei" },
  {name: "Brussels", timezones: "Europe/Brussels" },
  {name: "Bucharest", timezones: "Europe/Bucharest" },
  {name: "Budapest", timezones: "Europe/Budapest" },
  {name: "Buenos Aires", timezones: "America/Argentina/Buenos_Aires" },
  {name: "Bujumbura", timezones: "Africa/Bujumbura" },
  {name: "Busingen", timezones: "Europe/Busingen" },
  {name: "Cairo", timezones: "Africa/Cairo" },
  {name: "Cambridge Bay", timezones: "America/Cambridge_Bay" },
  {name: "Campo Grande", timezones: "America/Campo_Grande" },
  {name: "Canary", timezones: "Atlantic/Canary" },
  {name: "Cancun", timezones: "America/Cancun" },
  {name: "Cape Verde", timezones: "Atlantic/Cape_Verde" },
  {name: "Caracas", timezones: "America/Caracas" },
  {name: "Casablanca", timezones: "Africa/Casablanca" },
  {name: "Casey", timezones: "Antarctica/Casey" },
  {name: "Catamarca", timezones: "America/Argentina/Catamarca" },
  {name: "Cayenne", timezones: "America/Cayenne" },
  {name: "Cayman", timezones: "America/Cayman" },
  {name: "Center", timezones: "America/North_Dakota/Center" },
  {name: "Ceuta", timezones: "Africa/Ceuta" },
  {name: "Chagos", timezones: "Indian/Chagos" },
  {name: "Chatham", timezones: "Pacific/Chatham" },
  {name: "Chicago", timezones: "America/Chicago" },
  {name: "Chihuahua", timezones: "America/Chihuahua" },
  {name: "Chisinau", timezones: "Europe/Chisinau" },
  {name: "Chita", timezones: "Asia/Chita" },
  {name: "Choibalsan", timezones: "Asia/Choibalsan" },
  {name: "Chongqing", timezones: "Asia/Chongqing" },
  {name: "Christmas", timezones: "Indian/Christmas" },
  {name: "Chuuk", timezones: "Pacific/Chuuk" },
  {name: "Cocos", timezones: "Indian/Cocos" },
  {name: "Colombo", timezones: "Asia/Colombo" },
  {name: "Comod Rivadavia", timezones: "America/Argentina/ComodRivadavia" },
  {name: "Conakry", timezones: "Africa/Conakry" },
  {name: "Continental", timezones: "America/Argentina/Catamarca" },
  {name: "Copenhagen", timezones: "Europe/Copenhagen" },
  {name: "Cordoba", timezones: "America/Argentina/Cordoba" },
  {name: "Costa Rica", timezones: "America/Costa_Rica" },
  {name: "Creston", timezones: "America/Creston" },
  {name: "Cuiaba", timezones: "America/Cuiaba" },
  {name: "Curacao", timezones: "America/Curacao" },
  {name: "Dacca", timezones: "Asia/Dacca" },
  {name: "Dakar", timezones: "Africa/Dakar" },
  {name: "Damascus", timezones: "Asia/Damascus" },
  {name: "Danmarkshavn", timezones: "America/Danmarkshavn" },
  {name: "Dar es Salaam", timezones: "Africa/Dar_es_Salaam" },
  {name: "Darwin", timezones: "Australia/Darwin" },
  {name: "Davis", timezones: "Antarctica/Davis" },
  {name: "Dawson", timezones: "America/Dawson" },
  {name: "Dawson Creek", timezones: "America/Dawson_Creek" },
  {name: "Denver", timezones: "America/Denver" },
  {name: "Detroit", timezones: "America/Detroit" },
  {name: "Dhaka", timezones: "Asia/Dhaka" },
  {name: "Dili", timezones: "Asia/Dili" },
  {name: "Djibouti", timezones: "Africa/Djibouti" },
  {name: "Dominica", timezones: "America/Dominica" },
  {name: "Douala", timezones: "Africa/Douala" },
  {name: "Dubai", timezones: "Asia/Dubai" },
  {name: "Dublin", timezones: "Europe/Dublin" },
  {name: "DumontDUrville", timezones: "Antarctica/DumontDUrville" },
  {name: "Dushanbe", timezones: "Asia/Dushanbe" },
  {name: "Easter", timezones: "Pacific/Easter" },
  {name: "East Timor", timezones: "Asia/Dili" },
  {name: "Edmonton", timezones: "America/Edmonton" },
  {name: "Efate", timezones: "Pacific/Efate" },
  {name: "Eire", timezones: "Europe/Dublin" },
  {name: "El Aaiun", timezones: "Africa/El_Aaiun" },
  {name: "El Salvador", timezones: "America/El_Salvador" },
  {name: "Enderbury", timezones: "Pacific/Enderbury" },
  {name: "Ensenada", timezones: "America/Tijuana" },
  {name: "Eucla", timezones: "Australia/Eucla" },
  {name: "Fakaofo", timezones: "Pacific/Fakaofo" },
  {name: "Faroe", timezones: "Atlantic/Faroe" },
  {name: "Fiji", timezones: "Pacific/Fiji" },
  {name: "Fort Nelson", timezones: "America/Fort_Nelson" },
  {name: "Fortaleza", timezones: "America/Fortaleza" },
  {name: "France", timezones: "Europe/Paris" },
  {name: "Fredericton", timezones: "America/Moncton" },
  {name: "Freetown", timezones: "Africa/Freetown" },
  {name: "Funafuti", timezones: "Pacific/Funafuti" },
  {name: "Gabon", timezones: "Africa/Libreville" },
  {name: "Galapagos", timezones: "Pacific/Galapagos" },
  {name: "Gambier", timezones: "Pacific/Gambier" },
  {name: "Gaza", timezones: "Asia/Gaza" },
  {name: "Gibraltar", timezones: "Europe/Gibraltar" },
  {name: "Glace Bay", timezones: "America/Glace_Bay" },
  {name: "Godthab", timezones: "America/Godthab" },
  {name: "Goose Bay", timezones: "America/Goose_Bay" },
  {name: "Grand Turk", timezones: "America/Grand_Turk" },
  {name: "Grenada", timezones: "America/Grenada" },
  {name: "Guadeloupe", timezones: "America/Guadeloupe" },
  {name: "Guam", timezones: "Pacific/Guam" },
  {name: "Guatemala", timezones: "America/Guatemala" },
  {name: "Guayaquil", timezones: "America/Guayaquil" },
  {name: "Guernsey", timezones: "Europe/Guernsey" },
  {name: "Guyana", timezones: "America/Guyana" },
  {name: "Halifax", timezones: "America/Halifax" },
  {name: "Harare", timezones: "Africa/Harare" },
  {name: "Harbin", timezones: "Asia/Harbin" },
  {name: "Havana", timezones: "America/Havana" },
  {name: "Hebron", timezones: "Asia/Hebron" },
  {name: "Helsinki", timezones: "Europe/Helsinki" },
  {name: "Hermosillo", timezones: "America/Hermosillo" },
  {name: "Ho Chi Minh", timezones: "Asia/Ho_Chi_Minh" },
  {name: "Hong Kong", timezones: "Asia/Hong_Kong" },
  {name: "Honolulu", timezones: "Pacific/Honolulu" },
  {name: "Hovd", timezones: "Asia/Hovd" },
  {name: "Hudson", timezones: "America/Hudson" },
  {name: "Humboldt", timezones: "America/North_Dakota/New_Salem" },
  {name: "Hyderabad", timezones: "Asia/Kolkata" },{ name: "Iceland", timezones: "Atlantic/Reykjavik" },
  {name: "Indianapolis", timezones: "America/Indianapolis" },
  {name: "Inuvik", timezones: "America/Inuvik" },
  {name: "Iqaluit", timezones: "America/Iqaluit" },
  {name: "Irkutsk", timezones: "Asia/Irkutsk" },
  {name: "Isle of Man", timezones: "Europe/Isle_of_Man" },
  {name: "Istanbul", timezones: "Europe/Istanbul" },
  {name: "Jakarta", timezones: "Asia/Jakarta" },
  {name: "Jamaica", timezones: "America/Jamaica" },
  {name: "Jan Mayen", timezones: "Atlantic/Jan_Mayen" },
  {name: "Jayapura", timezones: "Asia/Jayapura" },
  {name: "Jerusalem", timezones: "Asia/Jerusalem" },
  {name: "Johannesburg", timezones: "Africa/Johannesburg" },
  {name: "Johnston", timezones: "Pacific/Johnston" },
  {name: "Juba", timezones: "Africa/Juba" },
  {name: "Jujuy", timezones: "America/Jujuy" },
  {name: "Juneau", timezones: "America/Juneau" },
  {name: "Kabul", timezones: "Asia/Kabul" },
  {name: "Kaliningrad", timezones: "Europe/Kaliningrad" },
  {name: "Kamchatka", timezones: "Asia/Kamchatka" },
  {name: "Kampala", timezones: "Africa/Kampala" },
  {name: "Karachi", timezones: "Asia/Karachi" },
  {name: "Kashgar", timezones: "Asia/Kashgar" },
  {name: "Kathmandu", timezones: "Asia/Kathmandu" },
  {name: "Katmandu", timezones: "Asia/Katmandu" },
  {name: "Khandyga", timezones: "Asia/Khandyga" },
  {name: "Khartoum", timezones: "Africa/Khartoum" },
  {name: "Kiev", timezones: "Europe/Kiev" },
  {name: "Kigali", timezones: "Africa/Kigali" },
  {name: "Kinshasa", timezones: "Africa/Kinshasa" },
  {name: "Kiritimati", timezones: "Pacific/Kiritimati" },
  {name: "Knox IN", timezones: "America/Knox_IN" },
  {name: "Kolkata", timezones: "Asia/Kolkata" },
  {name: "Kralendijk", timezones: "America/Kralendijk" },
  {name: "Krasnoyarsk", timezones: "Asia/Krasnoyarsk" },
  {name: "Kuala Lumpur", timezones: "Asia/Kuala_Lumpur" },
  {name: "Kuching", timezones: "Asia/Kuching" },
  {name: "Kuwait", timezones: "Asia/Kuwait" },
  {name: "Kwajalein", timezones: "Pacific/Kwajalein" },
  {name: "La Paz", timezones: "America/La_Paz" },
  {name: "La Rioja", timezones: "America/Argentina/La_Rioja" },
  {name: "Lagos", timezones: "Africa/Lagos" },
  {name: "Libreville", timezones: "Africa/Libreville" },
  {name: "Lima", timezones: "America/Lima" },
  {name: "Lindeman", timezones: "Australia/Lindeman" },
  {name: "Lisbon", timezones: "Europe/Lisbon" },
  {name: "Ljubljana", timezones: "Europe/Ljubljana" },
  {name: "Lome", timezones: "Africa/Lome" },
  {name: "London", timezones: "Europe/London" },
  {name: "Longyearbyen", timezones: "Arctic/Longyearbyen" },
  {name: "Lord Howe", timezones: "Australia/Lord_Howe" },
  {name: "Los Angeles", timezones: "America/Los_Angeles" },
  {name: "Louisville", timezones: "America/Louisville" },
  {name: "Lower Princes", timezones: "America/Lower_Princes" },
  {name: "Luanda", timezones: "Africa/Luanda" },
  {name: "Lubumbashi", timezones: "Africa/Lubumbashi" },
  {name: "Lusaka", timezones: "Africa/Lusaka" },
  {name: "Luxembourg", timezones: "Europe/Luxembourg" },
  {name: "Macau", timezones: "Asia/Macau" },
  {name: "Maceio", timezones: "America/Maceio" },
  {name: "Macedonia", timezones: "Europe/Skopje" },
  {name: "Madeira", timezones: "Atlantic/Madeira" },
  {name: "Madrid", timezones: "Europe/Madrid" },
  {name: "Magadan", timezones: "Asia/Magadan" },
  {name: "Mahe", timezones: "Indian/Mahe" },
  {name: "Majuro", timezones: "Pacific/Majuro" },
  {name: "Makassar", timezones: "Asia/Makassar" },
  {name: "Malabo", timezones: "Africa/Malabo" },
  {name: "Malawi", timezones: "Africa/Blantyre" },
  {name: "Maldives", timezones: "Indian/Maldives" },
  {name: "Mali", timezones: "Africa/Bamako" },
  {name: "Malta", timezones: "Europe/Malta" },
  {name: "Managua", timezones: "America/Managua" },
  {name: "Manaus", timezones: "America/Manaus" },
  {name: "Manila", timezones: "Asia/Manila" },
  {name: "Maputo", timezones: "Africa/Maputo" },
  {name: "Marengo", timezones: "America/Indiana/Marengo" },
  {name: "Mariehamn", timezones: "Europe/Mariehamn" },
  {name: "Marigot", timezones: "America/Marigot" },
  {name: "Marquesas", timezones: "Pacific/Marquesas" },
  {name: "Martinique", timezones: "America/Martinique" },
  {name: "Maseru", timezones: "Africa/Maseru" },
  {name: "Matamoros", timezones: "America/Matamoros" },
  {name: "Mauritius", timezones: "Indian/Mauritius" },
  {name: "Mayotte", timezones: "Indian/Mayotte" },
  {name: "Mazatlan", timezones: "America/Mazatlan" },
  {name: "Mbabane", timezones: "Africa/Mbabane" },
  {name: "McMurdo", timezones: "Antarctica/McMurdo" },
  {name: "Melbourne", timezones: "Australia/Melbourne" },
  {name: "Mendoza", timezones: "America/Argentina/Mendoza" },
  {name: "Menominee", timezones: "America/Menominee" },
  {name: "Merida", timezones: "America/Merida" },
  {name: "Metlakatla", timezones: "America/Metlakatla" },
  {name: "Mexico City", timezones: "America/Mexico_City" },
  {name: "Miquelon", timezones: "America/Miquelon" },
  {name: "Minsk", timezones: "Europe/Minsk" },
  {name: "Mogadishu", timezones: "Africa/Mogadishu" },
  {name: "Monaco", timezones: "Europe/Monaco" },
  {name: "Moncton", timezones: "America/Moncton" },
  {name: "Monrovia", timezones: "Africa/Monrovia" },
  {name: "Monterrey", timezones: "America/Monterrey" },
  {name: "Montevideo", timezones: "America/Montevideo" },
  {name: "Monticello", timezones: "America/Kentucky/Monticello" },
  {name: "Montreal", timezones: "America/Montreal" },
  {name: "Montserrat", timezones: "America/Montserrat" },
  {name: "Moscow", timezones: "Europe/Moscow" },
  {name: "Muscat", timezones: "Asia/Muscat" },
  {name: "Nairobi", timezones: "Africa/Nairobi" },
  {name: "Namibia", timezones: "Africa/Windhoek" },
  {name: "Nassau", timezones: "America/Nassau" },
  {name: "Nauru", timezones: "Pacific/Nauru" },
  {name: "Ndjamena", timezones: "Africa/Ndjamena" },
  {name: "New Salem", timezones: "America/North_Dakota/New_Salem" },
  {name: "New York", timezones: "America/New_York" },
  {name: "Niamey", timezones: "Africa/Niamey" },
  {name: "Nicosia", timezones: "Asia/Nicosia" },
  {name: "Nipigon", timezones: "America/Nipigon" },
  {name: "Niue", timezones: "Pacific/Niue" },
  {name: "Nome", timezones: "America/Nome" },
  {name: "Norfolk", timezones: "Pacific/Norfolk" },
  {name: "Noronha", timezones: "America/Noronha" },
  {name: "North Dakota Center", timezones: "America/North_Dakota/Center" },
  {name: "Nouakchott", timezones: "Africa/Nouakchott" },
  {name: "Noumea", timezones: "Pacific/Noumea" },
  {name: "Novokuznetsk", timezones: "Asia/Novokuznetsk" },
  {name: "Novosibirsk", timezones: "Asia/Novosibirsk" },
  {name: "Ojinaga", timezones: "America/Ojinaga" },
  {name: "Omsk", timezones: "Asia/Omsk" },
  {name: "Oral", timezones: "Asia/Oral" },
  {name: "Oslo", timezones: "Europe/Oslo" },
  {name: "Ouagadougou", timezones: "Africa/Ouagadougou" },
  {name: "Pago Pago", timezones: "Pacific/Pago_Pago" },
  {name: "Palau", timezones: "Pacific/Palau" },
  {name: "Palmer", timezones: "Antarctica/Palmer" },
  {name: "Panama", timezones: "America/Panama" },
  {name: "Pangnirtung", timezones: "America/Pangnirtung" },
  {name: "Paramaribo", timezones: "America/Paramaribo" },
  {name: "Paris", timezones: "Europe/Paris" },
  {name: "Perth", timezones: "Australia/Perth" },
  {name: "Petersburg", timezones: "America/Indiana/Petersburg" },
  {name: "Phnom Penh", timezones: "Asia/Phnom_Penh" },
  {name: "Phoenix", timezones: "America/Phoenix" },
  {name: "Pitcairn", timezones: "Pacific/Pitcairn" },
  {name: "Podgorica", timezones: "Europe/Podgorica" },
  {name: "Pohnpei", timezones: "Pacific/Pohnpei" },
  {name: "Pontianak", timezones: "Asia/Pontianak" },
  {name: "Port-au-Prince", timezones: "America/Port-au-Prince" },
  {name: "Port Moresby", timezones: "Pacific/Port_Moresby" },
  {name: "Port of Spain", timezones: "America/Port_of_Spain" },
  {name: "Porto Velho", timezones: "America/Porto_Velho" },
  {name: "Portugal", timezones: "Europe/Lisbon" },
  {name: "Prague", timezones: "Europe/Prague" },
  {name: "Puerto Rico", timezones: "America/Puerto_Rico" },
  {name: "Punta Arenas", timezones: "America/Punta_Arenas" },
  {name: "Pyongyang", timezones: "Asia/Pyongyang" },
  {name: "Qatar", timezones: "Asia/Qatar" },
  {name: "Qyzylorda", timezones: "Asia/Qyzylorda" },
  {name: "Rainy River", timezones: "America/Rainy_River" },
  {name: "Rangoon", timezones: "Asia/Rangoon" },
  {name: "Rankin Inlet", timezones: "America/Rankin_Inlet" },
  {name: "Rarotonga", timezones: "Pacific/Rarotonga" },
  {name: "Recife", timezones: "America/Recife" },
  {name: "Regina", timezones: "America/Regina" },
  {name: "Resolute", timezones: "America/Resolute" },
  {name: "Reunion", timezones: "Indian/Reunion" },
  {name: "Reykjavik", timezones: "Atlantic/Reykjavik" },
  {name: "Riga", timezones: "Europe/Riga" },
  {name: "Rio Branco", timezones: "America/Rio_Branco" },
  {name: "Rio Gallegos", timezones: "America/Argentina/Rio_Gallegos" },
  {name: "Riyadh", timezones: "Asia/Riyadh" },
  {name: "Rome", timezones: "Europe/Rome" },
  {name: "Rosario", timezones: "America/Argentina/Rosario" },
  {name: "Saipan", timezones: "Pacific/Saipan" },
  {name: "Sakhalin", timezones: "Asia/Sakhalin" },
  {name: "Salta", timezones: "America/Argentina/Salta" },
  {name: "Salt Lake City", timezones: "America/Denver" },
  {name: "San Juan", timezones: "America/Puerto_Rico" },
  {name: "San Luis", timezones: "America/Argentina/San_Luis" },
  {name: "San Marino", timezones: "Europe/San_Marino" },
  {name: "Santa Isabel", timezones: "America/Santa_Isabel" },
  {name: "Santarem", timezones: "America/Santarem" },
  {name: "Santiago", timezones: "America/Santiago" },
  {name: "Santo Domingo", timezones: "America/Santo_Domingo" },
  {name: "Sao Paulo", timezones: "America/Sao_Paulo" },
  {name: "Scoresbysund", timezones: "America/Scoresbysund" },
  {name: "Seoul", timezones: "Asia/Seoul" },
  {name: "Shanghai", timezones: "Asia/Shanghai" },
  {name: "Simferopol", timezones: "Europe/Simferopol" },
  {name: "Singapore", timezones: "Asia/Singapore" },
  {name: "Sitka", timezones: "America/Sitka" },
  {name: "Skopje", timezones: "Europe/Skopje" },
  {name: "Sofia", timezones: "Europe/Sofia" },
  {name: "South Georgia", timezones: "Atlantic/South_Georgia" },
  {name: "Srednekolymsk", timezones: "Asia/Srednekolymsk" },
  {name: "Sri Jayawardenepura", timezones: "Asia/Colombo" },
  {name: "St Barthelemy", timezones: "America/St_Barthelemy" },
  {name: "St Helena", timezones: "Atlantic/St_Helena" },
  {name: "St Johns", timezones: "America/St_Johns" },
  {name: "St Kitts", timezones: "America/St_Kitts" },
  {name: "St Lucia", timezones: "America/St_Lucia" },
  {name: "St Thomas", timezones: "America/St_Thomas" },
  {name: "St Vincent", timezones: "America/St_Vincent" },
  {name: "Stanley", timezones: "Atlantic/Stanley" },
  {name: "Stockholm", timezones: "Europe/Stockholm" },
  {name: "Swift Current", timezones: "America/Swift_Current" },
  {name: "Sydney", timezones: "Australia/Sydney" },
  {name: "Tahiti", timezones: "Pacific/Tahiti" },
  {name: "Taipei", timezones: "Asia/Taipei" },
  {name: "Tallinn", timezones: "Europe/Tallinn" },
  {name: "Tashkent", timezones: "Asia/Tashkent" },
  {name: "Tbilisi", timezones: "Asia/Tbilisi" },
  {name: "Tegucigalpa", timezones: "America/Tegucigalpa" },
  {name: "Tehran", timezones: "Asia/Tehran" },
  {name: "Tell City", timezones: "America/Indiana/Tell_City" },
  {name: "Thimphu", timezones: "Asia/Thimphu" },
  {name: "Thule", timezones: "America/Thule" },
  {name: "Thunder Bay", timezones: "America/Thunder_Bay" },
  {name: "Tijuana", timezones: "America/Tijuana" },
  {name: "Tirane", timezones: "Europe/Tirane" },
  {name: "Tokyo", timezones: "Asia/Tokyo" },
  {name: "Tongatapu", timezones: "Pacific/Tongatapu" },
  {name: "Toronto", timezones: "America/Toronto" },
  {name: "Tortola", timezones: "America/Tortola" },
  {name: "Tripoli", timezones: "Africa/Tripoli" },
  {name: "Troll", timezones: "Antarctica/Troll" },
  {name: "Tunis", timezones: "Africa/Tunis" },
  {name: "Ulaanbaatar", timezones: "Asia/Ulaanbaatar" },
  {name: "Ulyanovsk", timezones: "Europe/Ulyanovsk" },
  {name: "Urumqi", timezones: "Asia/Urumqi" },
  {name: "Ushuaia", timezones: "America/Argentina/Ushuaia" },
  {name: "Ust-Nera", timezones: "Asia/Ust-Nera" },
  {name: "Vaduz", timezones: "Europe/Vaduz" },
  {name: "Vancouver", timezones: "America/Vancouver" },
  {name: "Vatican", timezones: "Europe/Vatican" },
  {name: "Vevay", timezones: "America/Indiana/Vevay" },
  {name: "Vientiane", timezones: "Asia/Vientiane" },
  {name: "Vienna", timezones: "Europe/Vienna" },
  {name: "Vilnius", timezones: "Europe/Vilnius" },
  {name: "Vincennes", timezones: "America/Indiana/Vincennes" },
  {name: "Virgin", timezones: "America/Virgin" },
  {name: "Vladivostok", timezones: "Asia/Vladivostok" },
  {name: "Volgograd", timezones: "Europe/Volgograd" },
  {name: "Vostok", timezones: "Antarctica/Vostok" },
  {name: "Wake", timezones: "Pacific/Wake" },
  {name: "Wallis", timezones: "Pacific/Wallis" },
  {name: "Warsaw", timezones: "Europe/Warsaw" },
  {name: "Whitehorse", timezones: "America/Whitehorse" },
  {name: "Winamac", timezones: "America/Indiana/Winamac" },
  {name: "Windhoek", timezones: "Africa/Windhoek" },
  {name: "Winnipeg", timezones: "America/Winnipeg" },
  {name: "Yakutat", timezones: "America/Yakutat" },
  {name: "Yakutsk", timezones: "Asia/Yakutsk" },
  {name: "Yekaterinburg", timezones: "Asia/Yekaterinburg" },
  {name: "Yellowknife", timezones: "America/Yellowknife" },
  {name: "Yerevan", timezones: "Asia/Yerevan" },
  {name: "Zagreb", timezones: "Europe/Zagreb" },
  {name: "Zaporozhye", timezones: "Europe/Zaporozhye" },
  {name: "Zurich", timezones: "Europe/Zurich" }
];

let selectElement = document.querySelector("#city");
let option;

citiesArray.forEach(function(city){
    option = new Option(city.name, city.timezones)
    selectElement.add(option)
});

selectElement.addEventListener("change", function(event){
    let myCityElement = document.querySelector(".my-city");
    myCityElement.style.display = "none";

    let citiesElement = document.querySelector(".cities");
    citiesElement.style.display = "none";

    let selectedCityElement = document.querySelector(".selectedCity");
    selectedCityElement.style.display = "flex"

    let sdCityName = selectedCityElement.querySelector(".sdCityName");
    citiesArray.forEach(function(sdCity){
        if(sdCity.timezones === event.target.value){
            sdCityName.innerHTML = sdCity.name;
            return true;
        };
    });

    let sdCityDate = selectedCityElement.querySelector(".sdCityDate");
    sdCityDate.innerHTML = moment.tz(event.target.value).format("dddd, Do MMMM YYYY");

    let sdCityTime = selectedCityElement.querySelector(".sdCityTime");
    sdCityTime.innerHTML = moment.tz(event.target.value).format("hh:mm A");

    if(event.target.value === ""){
        myCityElement.style.display = "flex";
        citiesElement.style.display = "flex";
        selectedCityElement.style.display = "none";
    };
});

let myCityGuess = moment.tz.guess();
let myCityTimeElement = document.querySelector(".my-city-time");
myCityTimeElement.innerHTML = moment.tz(myCityGuess).format("hh:mm A");
let myCityDetailName = document.querySelector(".mycityname");
let myCityName;

citiesArray.forEach(function(cities){
    if(cities.timezones === myCityGuess){
        myCityName = cities.name;
    }
});

myCityDetailName.innerHTML = myCityName;
let myCityDetailDate = document.querySelector(".mycitydate");
myCityDetailDate.innerHTML = moment.tz(myCityGuess).format("dddd, Do MMMM YYYY");

let randomNumberOne = Math.floor(Math.random() * citiesArray.length) + 1;
let randomCityOne = citiesArray[(randomNumberOne + 1)];
let cityOne = document.querySelector("#cityOne");
let cityOneLabel = cityOne.querySelector(".cityLabel");
cityOneLabel.innerHTML = randomCityOne.name;
let cityOneDate = cityOne.querySelector(".date");
cityOneDate.innerHTML = moment.tz(randomCityOne.timezones).format("dddd, [<br />] Do MMMM YYYY");
let cityOneHour = cityOne.querySelector(".hour");
cityOneHour.innerHTML = moment.tz(randomCityOne.timezones).format("hh");
let cityOneMin = cityOne.querySelector(".min");
cityOneMin.innerHTML = moment.tz(randomCityOne.timezones).format("mm");
let cityOnePeriod = cityOne.querySelector(".period");
cityOnePeriod.innerHTML = moment.tz(randomCityOne.timezones).format("A");

let randomNumberTwo = Math.floor(Math.random() * citiesArray.length) + 1;
let randomCityTwo = citiesArray[(randomNumberTwo + 1)];
let cityTwo = document.querySelector("#cityTwo");
let cityTwoLabel = cityTwo.querySelector(".cityLabel");
cityTwoLabel.innerHTML = randomCityTwo.name;
let cityTwoDate = cityTwo.querySelector(".date");
cityTwoDate.innerHTML = moment.tz(randomCityTwo.timezones).format("dddd, [<br />] Do MMMM YYYY");
let cityTwoHour = cityTwo.querySelector(".hour");
cityTwoHour.innerHTML = moment.tz(randomCityTwo.timezones).format("hh");
let cityTwoMin = cityTwo.querySelector(".min");
cityTwoMin.innerHTML = moment.tz(randomCityTwo.timezones).format("mm");
let cityTwoPeriod = cityTwo.querySelector(".period");
cityTwoPeriod.innerHTML = moment.tz(randomCityTwo.timezones).format("A");

let randomNumberThree = Math.floor(Math.random() * citiesArray.length) + 1;
let randomCityThree = citiesArray[(randomNumberThree + 1)];
let cityThre = document.querySelector("#cityThree");
let cityThreeLabel = cityThree.querySelector(".cityLabel");
cityThreeLabel.innerHTML = randomCityThree.name;
let cityThreeDate = cityThree.querySelector(".date");
cityThreeDate.innerHTML = moment.tz(randomCityThree.timezones).format("dddd, [<br />] Do MMMM YYYY");
let cityThreeHour = cityThree.querySelector(".hour");
cityThreeHour.innerHTML = moment.tz(randomCityThree.timezones).format("hh");
let cityThreeMin = cityThree.querySelector(".min");
cityThreeMin.innerHTML = moment.tz(randomCityThree.timezones).format("mm");
let cityThreePeriod = cityThree.querySelector(".period");
cityThreePeriod.innerHTML = moment.tz(randomCityThree.timezones).format("A");